"""
Django settings for Django_demo project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 当前项目的绝对路径
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 加密盐
SECRET_KEY = 'django-insecure-ndw#l&%6fo*i3)ou-2u3gx2uspmq(ik83mmuzv@lqje-t-5e&&'

# SECURITY WARNING: don't run with debug turned on in production!
# Debug调试模式 True:开启 | False:关闭
DEBUG = True

# 允许访问的ip（当DEBUG=False时，该项必须填写）
#                [] 仅允许本地访问
#             ['*'] 允许所有人访问
# ['192.168.8.204'] 仅允许指定ip访问
ALLOWED_HOSTS = ['*']


# Application definition
# 项目安装的应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 当前项目的根 URL，是 Django 路由系统的入口
ROOT_URLCONF = 'Django_demo.urls'

# 模板管理
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 数据库配置
DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': BASE_DIR / 'db.mysql',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test_plat',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
# 密码验证器
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# 语言配置项 en-us:英文 | zh-Hans:中文
LANGUAGE_CODE = 'zh-Hans'

# 时区配置项 UTC:世界时区 | Asia/Shanghai:中国时区
TIME_ZONE = 'Asia/Shanghai'

# 是否开启国际化功能/是否开启本地化功能
USE_I18N = True
USE_L10N = True

# 时区的处理方式(True:存储到数据库的时间是世界时间 'UTC')
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
# 静态资源的存放位置，静态资源包括 CSS、JS、Images
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 测试代码
if __name__ == '__main__':
    print(BASE_DIR)
