# Generated by Django 4.1.4 on 2023-01-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_mode', '0002_rename_name_test_test_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_string',
            new_name='test_str',
        ),
    ]
