# Generated by Django 4.1.4 on 2023-01-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mode', '0003_rename_test_string_test_test_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_user_name', models.CharField(max_length=64)),
                ('uid', models.CharField(max_length=10)),
                ('role_name', models.CharField(max_length=64)),
                ('role_id', models.CharField(max_length=64)),
                ('role_level', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_str',
            field=models.CharField(max_length=64),
        ),
    ]
